BMS/Controllers/MdController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BMS.Models;

namespace BMS.Controllers
{
    public class MdController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Md



        public ActionResult Index()
        {
            Session["Name"] = "Wellcome Manager";
            return View();
        }

        public ActionResult getUnauthTran()
        {
            var mangrTransections = db.MangrTransections.Include(m => m.Branch).Where(c=>c.Authorized==false);

            return View(mangrTransections.ToList());

        }

        public ActionResult EditTran(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MangrTransection mangrTransection = db.MangrTransections.Find(id);
            if (mangrTransection == null)
            {
                return HttpNotFound();
            }
            ViewBag.BranchId = new SelectList(db.Branches, "Id", "Name", mangrTransection.BranchId);
            return View(mangrTransection);
        }

        // POST: MangrTransections/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditTran([Bind(Include = "Id,BranchId,Amount,TransDate")] MangrTransection mangrTransection)
        {
            if (ModelState.IsValid)
            {
                MangrTransection m1 = db.MangrTransections.Find(mangrTransection.Id);
                m1.Authorized = true;

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BranchId = new SelectList(db.Branches, "Id", "Name", mangrTransection.BranchId);
            return View(mangrTransection);
        }

    }
}

BMS/Views/Md/EditTran.cshtml
@model BMS.Models.MangrTransection

@{
    ViewBag.Title = "EditTran";
    Layout = "~/Views/Md/mdView.cshtml";
}

<h2>EditTran</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MangrTransection</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.BranchId, "BranchId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BranchId",null , htmlAttributes: new { @class = "form-control"})
                @Html.ValidationMessageFor(model => model.BranchId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayTextFor(model => model.Amount)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TransDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayTextFor(model => model.TransDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Authorized, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Authorized)
                    @Html.ValidationMessageFor(model => model.Authorized, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BMS/Views/Md/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Md/mdView.cshtml";
}

<h2>@Session["Name"]</h2>

BMS/Views/Md/getUnauthTran.cshtml
@model IEnumerable<BMS.Models.MangrTransection>

@{
    ViewBag.Title = "getUnauthTran";
    Layout = "~/Views/Md/mdView.cshtml";
}

<h2>getUnauthTran</h2>

<p>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Branch.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TransDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Authorized)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Branch.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TransDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Authorized)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditTran", new { id=item.Id }) |

            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

BMS/Views/Md/mdView.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BMS", "Index", "Md", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Managers", "Index", "Managers")</li>
                    <li>@Html.ActionLink("Employees", "Index", "Employees")</li>
                    <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                    <li>@Html.ActionLink("Top Branches", "maxBalanceBraches", "Branches")</li>
                    <li>@Html.ActionLink("Notices ", "Index", "ManNoticeBoards")</li>
                    <li>@Html.ActionLink("Managers Salary", "Index", "ManSalaries")</li>
                    <li>@Html.ActionLink("Employee Salary", "Index", "EmpSalaries")</li>
                    <li>@Html.ActionLink("Authorize Transection", "getUnauthTran", "Md")</li>
                </ul>
            </div>
        </div>
    </div>

<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

BMS/Views/Md/test.cshtml
@model IEnumerable<BMS.Models.Branch>

@{
    ViewBag.Title = "test";
    Layout = "~/Views/Shared/_Managers.cshtml";
}

<h2>test</h2>

<p>

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CurrentEmployees)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CurrentManagers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BranchBalance)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CurrentEmployees)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CurrentManagers)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BranchBalance)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>